name: Rebuild IMG

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Set custom Maven settings.xml
      run: |
            mkdir -p $HOME/.m2
            cat > $HOME/.m2/settings.xml <<EOF
            <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                  http://maven.apache.org/xsd/settings-1.0.0.xsd">
            
              <activeProfiles>
                <activeProfile>github</activeProfile>
              </activeProfiles>
            
              <profiles>
                <profile>
                  <id>github</id>
                  <repositories>
                    <repository>
                      <id>central</id>
                      <url>https://repo1.maven.org/maven2</url>
                    </repository>
                    <repository>
                      <id>github</id>
                      <url>https://maven.pkg.github.com/shivenducs1136/chessgame</url>
                      <snapshots>
                        <enabled>true</enabled>
                      </snapshots>
                    </repository>
                  </repositories>
                </profile>
              </profiles>
            
              <servers>
                <server>
              <id>github</id>
                  <username>shivenducs1136</username>
                  <password>${{ secrets.PASSWORD }}</password>
                </server>
              </servers>
            </settings>
            EOF
    - name: Maven clean install 
      run: mvn clean install >> mvn.txt
    - name: Build the Docker image
      run: docker build -t chessgame:$(date +%s) -f Dockerfile .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: bitwisor07
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          tags: bitwisor07/chessgame:latest
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.PEM }}
      run: |
          echo "$SUPER_SECRET" | base64 --decode > kp.pem
    - name: Set permissions for SSH key
      run: chmod 600 kp.pem
    - name: SSH into EC2 and run multiple commands
      run: |
        ssh -o StrictHostKeyChecking=no -i kp.pem ec2-user@13.51.178.118 << 'EOF'
          sudo docker stop chessgamecontainer
          sudo docker rm chessgamecontainer
          sudo docker login --username bitwisor07 --password ${{ secrets.PASSWORD }}
          sudo docker pull bitwisor07/chessgame:latest
          sudo docker run --name=chessgamecontainer -d -p 50:8080 bitwisor07/chessgame:latest
        EOF
